export default {
  login: "chait04",
  id: 59140343,
  node_id: "MDQ6VXNlcjU5MTQwMzQz",
  avatar_url: "https://avatars0.githubusercontent.com/u/59140343?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/chait04",
  html_url: "https://github.com/chait04",
  followers_url: "https://api.github.com/users/chait04/followers",
  following_url: "https://api.github.com/users/chait04/following{/other_user}",
  gists_url: "https://api.github.com/users/chait04/gists{/gist_id}",
  starred_url: "https://api.github.com/users/chait04/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/chait04/subscriptions",
  organizations_url: "https://api.github.com/users/chait04/orgs",
  repos_url: "https://api.github.com/users/chait04/repos",
  events_url: "https://api.github.com/users/chait04/events{/privacy}",
  received_events_url: "https://api.github.com/users/chait04/received_events",
  type: "User",
  site_admin: false,
  name: "Chaitanya Khachane",
  company: null,
  blog: "",
  location: "Mumbai , India",
  email: null,
  hireable: null,
  bio: "REACT | Front end Developer | learning complex js\r\n",
  twitter_username: "chaitaanya04",
  public_repos: 49,
  public_gists: 1,
  followers: 0,
  following: 13,
  created_at: "2019-12-22T13:27:25Z",
  updated_at: "2020-12-31T12:23:24Z",
};
